name: pomozen
description: A Pomodoro timer app with Minimal Design, offline support, and customizable settings.
version: 1.0.1+2

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ^3.32.4

dependencies:
  # Flutter core and localization
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  get: ^4.6.6

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5 # Path provider for device storage
  shared_preferences: ^2.2.3 # Persist simple key-value data

  # Device features and utilities
  torch_light: ^1.0.0 # Control device flashlight
  wakelock_plus: ^1.1.1 # Keep the screen awake
  permission_handler: ^11.3.1 # Handle permissions
  do_not_disturb: ^1.0.3 # Manage Do Not Disturb mode
  flutter_timezone: ^4.1.1 # Get device timezone
  android_intent_plus: ^5.3.0 # For Android intents
  url_launcher: ^6.3.1 # Launch URLs (updated version)
  package_info_plus: ^8.3.0 # Get package information
  device_info_plus: ^11.4.0 # Device information

  # UI and Widgets
  fl_chart: ^1.0.0 # For charts
  fluttertoast: ^8.2.8 # Toast messages
  flutter_heatmap_calendar: ^1.0.5 # Heatmap calendar widget
  pie_chart_sz: ^1.1.1 # Pie chart widget
  smooth_corner: ^1.1.1 # For smooth corners (updated version)
  flutter_colorpicker: ^1.0.3 # Color picker UI

  # Notifications
  flutter_local_notifications: ^17.2.3 # Local notifications
  awesome_notifications: ^0.10.1 # Powerful notification system

  # Data handling
  csv: ^6.0.0 # CSV parsing
  file_picker: ^10.1.9 # File picking
  intl: ^0.20.2 # Internationalization and date formatting
  nothing_glyph_interface: ^0.0.7 # Glyph interface utility


dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Build tools
  build_runner: ^2.4.15
  hive_generator: ^2.0.1

flutter_gen:
  synthetic-package: false

flutter:
  uses-material-design: true
  generate: true

  # Assets
  assets:
    - lib/l10n/
    - assets/app_icon.png

  # Fonts
  fonts:
    - family: OpenRunde
      fonts:
        - asset: assets/fonts/OpenRunde-Regular.otf
        - asset: assets/fonts/OpenRunde-Medium.otf
          weight: 500
        - asset: assets/fonts/OpenRunde-Semibold.otf
          weight: 600
        - asset: assets/fonts/OpenRunde-Bold.otf
          weight: 700